### ISSUE TITLE
Permission denied: 'config/settings_config.json'

### ISSUE THREAD

**Issue by OwenVey** [TheWicklowWolf/RadaRec#1]
When starting up the container, i get the following error message in the logs:
```
[2024-05-24 08:36:03 -0500] [1] [INFO] Starting gunicorn 22.0.0
[2024-05-24 08:36:03 -0500] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2024-05-24 08:36:03 -0500] [1] [INFO] Using worker: geventwebsocket.gunicorn.workers.GeventWebSocketWorker
[2024-05-24 08:36:03 -0500] [7] [INFO] Booting worker with pid: 7
Error Saving Config: [Errno 13] Permission denied: 'config/settings_config.json'
```

And here is my `compose.yaml`:
```yaml
services:
  radarec:
    image: thewicklowwolf/radarec
    container_name: radarec
    restart: unless-stopped
    environment:
      radarr_address: ${RADARR_URL}
      radarr_api_key: ${RADARR_API_KEY}
      tmdb_api_key: ${TMDB_API_KEY}
      quality_profile_id: 8
      language_choice: en
    volumes:
      - ./config/radarec:/radarec/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5000:5000
```

I have also tried adding `user: 1000:1000` as well as adding
```yaml
PUID: 1000
PGID: 1000
  ```
to `environment:` as that as how I run a lot of my arr containers but no luck. Let me know if you have any ideas! I'm running docker in an unprivileged LXC on Proxmox for context.

**Comment by TheWicklowWolf** [comment]
The directory `/radarec/config` needs write access with PUID:PGID to be 1000:1000, so for your directory `./config/radarec` can you confirm this is the case?

**Comment by OwenVey** [comment]
Ah looks like radarec automatically creates the config folder as `root:root`. A simple `chown` fixed the issue, thanks! Would be nice if you could automatically respect the `PUID` and `GUID` passed in when creating the config folder.

**Comment by TheWicklowWolf** [comment]
I just don't want to change permissions on folders.
